services:
  pythonapp:
    build: ./python/
    restart: always
    command: sh -c "sleep 50s ; python3 ./hello_world.py"
    depends_on:
      - mysql

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
